apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30080
    - port: 9901
      targetPort: admin
      protocol: TCP
      name: admin
      nodePort: 30901
  selector:
    app: envoy 