apiVersion: v1
kind: Service
metadata:
  name: citus-coordinator
spec:
  type: NodePort
  selector:
    app: citus-coordinator
  ports:
    - protocol: TCP
      port: {{ .Values.coordinator.ports }}
      targetPort: {{ .Values.coordinator.ports }}
      nodePort: 30000