apiVersion: v1
kind: Service
metadata:
  name: citus-worker
  labels:
    app: citus-worker
spec:
  clusterIP: None
  selector:
    app: citus-worker
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
